Repository Network-Leader/Homepage-FE, pull requests merged in 2022-07, with the labels that each got.

#76 TUI Calendar
  package-lock.json
  package.json
  src/components/calendar/TuiCalendar.tsx
  src/components/calendar/TuiCalendarWrapper.tsx
  src/hooks/useFetch.tsx
  src/pages/_app.tsx
  src/pages/api/calendar/calendars.tsx
  src/pages/api/calendar/schedules.tsx
  src/pages/calendar.tsx
Labels: ✨ feature

#72 Refactor/#63/my page
  src/components/home/slider.tsx
  src/components/myPage/ActivityLog.tsx
  src/components/myPage/Profile.tsx
  src/pages/mypage.tsx
  src/pages/signup.tsx
  src/styles/global/Global.tsx
  src/styles/home/slider.tsx
  src/styles/home/studyStatus.tsx
  src/styles/layout/main/footer.tsx
  src/styles/layout/sign/globalSignBox.tsx
  src/styles/myPage/header.tsx
  src/styles/myPage/myPage.tsx
Labels: 🛠 update

#86 feat: activity page header close #84
  src/components/activity/Header.tsx
  src/components/activity/Masonry.tsx
  src/pages/activity.tsx
  src/styles/activity/activity.tsx
Labels: ✨ feature

#88 로그인, 회원가입, 마이페이지 리팩토링 및 버그 수정
  package-lock.json
  package.json
  src/components/activity/Header.tsx
  src/components/activity/Masonry.tsx
  src/components/calendar/TuiCalendar.tsx
  src/components/calendar/TuiCalendarWrapper.tsx
  src/components/common/SignLayout.tsx
  src/components/common/header/DropDown.tsx
  src/components/common/header/Navbar.tsx
  src/components/common/header/SideBlock.tsx
  src/components/common/header/user.tsx
  src/components/edustatus/EduStatusCard.tsx
  src/components/edustatus/EduStatusModal.tsx
  src/components/edustatus/index.tsx
  src/components/home/slider.tsx
  src/components/myPage/ActivityLog.tsx
  src/components/myPage/Profile.tsx
  src/components/signup/ExpiredTimer.tsx
  src/components/signup/SignUp.tsx
  src/components/signup/SignUpForm.tsx
  src/components/signup/VerifyEmailForm.tsx
  src/context/tokenState.tsx
  src/hooks/useFetch.tsx
  src/pages/_app.tsx
  src/pages/activity.tsx
  src/pages/api/calendar/calendars.tsx
  src/pages/api/calendar/schedules.tsx
  src/pages/calendar.tsx
  src/pages/course.tsx
  src/pages/index.tsx
  src/pages/mypage.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/styles/activity/activity.tsx
  src/styles/eduStatus/eduStatus.tsx
  src/styles/global/Global.tsx
  src/styles/home/slider.tsx
  src/styles/home/studyStatus.tsx
  src/styles/layout/main/footer.tsx
  src/styles/layout/main/header.tsx
  src/styles/layout/sign/globalSignBox.tsx
  src/styles/myPage/header.tsx
  src/styles/myPage/myPage.tsx
  src/themes/emotion.d.ts
  src/themes/theme.ts
Labels: 🐛 bug, ✨ feature, 🛠 update

#94 회원가입 오류 수정
  package-lock.json
  src/components/signup/SignUp.tsx
Labels: 🐛 bug

#97 Feat/#95/improve sign page
  src/components/signup/SignUp.tsx
  src/components/signup/SignUpForm.tsx
Labels: 🐛 bug

#98 [회원가입] 오류 수정 및 개선
  src/components/signup/SignUp.tsx
  src/components/signup/SignUpForm.tsx
  src/pages/signin.tsx
  src/styles/layout/sign/globalSignBox.tsx
Labels: 🐛 bug, ✨ feature

#100 Update appspec.yml and Add deploy.sh
  appspec.yml
  deploy.sh
Labels: 🧑‍🔧 DevOps

#99 Create main.yml
  .github/workflows/main.yml
  appspec.yml
  deploy.sh
Labels: 🧑‍🔧 DevOps

#101 Update appspec.yml
  appspec.yml
Labels: 🧑‍🔧 DevOps

#102 Update deploy.sh
  deploy.sh
Labels: 🧑‍🔧 DevOps

#103 Update deploy.sh
  deploy.sh
Labels: 🧑‍🔧 DevOps

#104 Update main.yml
  .github/workflows/main.yml
Labels: 🧑‍🔧 DevOps

#108 CICD 오류 수정
  .github/workflows/main.yml
  README.md
  appspec.yml
  deploy.sh
  scripts/deploy.sh
Labels: 🧑‍🔧 DevOps

#109 Devops feature - success CI/CD pipeline applied
  .github/workflows/main.yml
  README.md
  appspec.yml
  deploy.sh
  scripts/deploy.sh
  src/components/common/footer/Footer.tsx
Labels: 🧑‍🔧 DevOps
