Repository Network-Leader/Homepage-FE, pull requests merged in 2022-06, with the labels that each got.

#36 feat/#32/activityModal
  next.config.js
  src/components/activity/Masonry.tsx
  src/components/activity/MasonryModal.tsx
  src/components/common/header/SideBlock.tsx
  src/pages/_app.tsx
  src/styles/activity/activity.tsx
  src/styles/activity/activityModal.tsx
  src/styles/global/Global.tsx
  src/styles/layout/footer.tsx
  src/styles/layout/header.tsx
  src/styles/myPage/header.tsx
  src/themes/emotion.d.ts
  src/themes/theme.ts
Labels: ✨ feature

#40 fix: 주석 삭제
  src/components/common/header/SideBlock.tsx
Labels: 🐛 bug

#42 feat: issue설명과 동일 close #41
  package-lock.json
  package.json
  src/components/common/footer/Footer.tsx
  src/components/common/header/DropDown.tsx
  src/components/common/header/Header.tsx
  src/components/common/header/Navbar.tsx
  src/components/common/header/SideBlock.tsx
  src/components/common/sign/SignLayout.tsx
  src/pages/_app.tsx
  src/pages/signin.tsx
  src/pages/signup.tsx
  src/styles/global/Global.tsx
  src/styles/layout/main/footer.tsx
  src/styles/layout/main/header.tsx
  src/styles/layout/sign/globalSignBox.tsx
Labels: ✨ feature

#44 feat: 회원가입 뷰 구현 && 리액트 훅 폼 라이브러리 설치 close #43
  package-lock.json
  package.json
  src/components/common/sign/SignLayout.tsx
  src/pages/signup.tsx
  src/styles/layout/sign/globalSignBox.tsx
Labels: ✨ feature

#48 feat/#12/mainpage apply
  src/components/home/ApplyButton/index.tsx
  src/components/home/YoutubePlayer/index.tsx
  src/pages/index.tsx
  src/styles/common.tsx
  src/styles/home/applyButton.tsx
Labels: ✨ feature

#50 update: Change apply button to full size
  src/styles/home/applyButton.tsx
Labels: ✨ feature

#53 fix: Align infos
  src/components/common/footer/Footer.tsx
  src/styles/layout/main/footer.tsx
Labels: 🐛 bug

#55 feat: made rotate slider responively close #45
  src/components/common/Layout.tsx
  src/components/home/slider.tsx
  src/pages/index.tsx
  src/styles/global/Global.tsx
  src/styles/home/slider.tsx
  src/styles/layout/main/header.tsx
  src/styles/layout/sign/globalSignBox.tsx
  src/themes/emotion.d.ts
  src/themes/theme.ts
Labels: ✨ feature

#59 dependency: Remove react-router-dom
  package-lock.json
  package.json
  src/pages/_app.tsx
Labels: 📦 dependency

#61 Feat/#57/reg ex insectation
  src/components/common/sign/SignLayout.tsx
  src/components/home/slider.tsx
  src/pages/signup.tsx
  src/styles/home/slider.tsx
  src/styles/layout/sign/globalSignBox.tsx
Labels: ✨ feature
